# Generated by Django 2.0.6 on 2020-04-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200412_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
