# Generated by Django 2.0.6 on 2020-04-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20200414_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='category',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='所属模块'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='static_html',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='要加载html'),
        ),
    ]
