# Generated by Django 2.0.6 on 2020-04-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('score', models.SmallIntegerField()),
                ('author', models.CharField(max_length=20)),
                ('announcer', models.CharField(max_length=20)),
                ('chapter_count', models.IntegerField()),
                ('album_info', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('publish_time', models.DateTimeField()),
                ('upload_time', models.DateTimeField()),
                ('cover', models.ImageField(upload_to='album_picture')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('url', models.CharField(max_length=20)),
                ('time_long', models.SmallIntegerField()),
                ('album_id', models.IntegerField()),
            ],
        ),
    ]
