# Generated by Django 2.0.6 on 2020-04-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_chapter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
