# Generated by Django 2.0.6 on 2020-04-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20200413_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='size',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='time_long',
            field=models.CharField(max_length=200),
        ),
    ]
