# Generated by Django 2.0.6 on 2020-04-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_auto_20200413_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='audio',
            field=models.ImageField(null=True, upload_to='audio'),
        ),
    ]
