# Generated by Django 2.0.6 on 2020-04-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_chapter_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='publish_time',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='upload_time',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
